# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    # le cache
    resolvers:
        cache_provider:
            web_path:
                web_root: "%kernel.project_dir%/public"

    cache: cache_provider

    webp:
        generate: true

    default_filter_set_settings:
        format: webp

    filter_sets:
        cache: ~

        thumbnail:
            quality: 25

        thumbnail_medium:
            quality: 50

    # L'endroit où sont stockées les vraies images.
    loaders:

    twig:
        mode: lazy

when@dev:
    liip_imagine:
        loaders:
            default:
                filesystem:
                    data_root:
                        - 'images/photo'

when@prod:
    liip_imagine:
        loaders:
            default:
                filesystem:
                    data_root:
                        - '%kernel.project_dir%/../uploaded-files/images/photo'
        resolvers:
            cache_provider:
                web_path:
                    web_root: "%kernel.project_dir%/../uploaded-files"
