# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    # le cache
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~

        # the name of the "filter set"
        thumbnail:

            # adjust the image quality to 50%
            quality: 50

            # list of transformations to apply (the "filters")
            filters:

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [350, 200], mode: outbound }

    # L'endroit où sont stockées les vraies images.
    loaders:

    twig:
        mode: lazy

when@dev:
    liip_imagine:
        loaders:
            default:
                filesystem:
                    data_root:
                        - 'images/photo'

when@prod:
    liip_imagine:
        loaders:
            default:
                filesystem:
                    data_root:
                        - '%kernel.project_dir%/../uploaded-files/images/photo'
