framework:
    default_locale: fr
    translator:
        default_path: '%kernel.project_dir%/translations'
        paths:
            - '%kernel.project_dir%/translations/fr'
        fallbacks:
            - fr
