twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'form/ckeditor.html.twig'
        - 'form/gallery.html.twig'
        - 'form/theme.html.twig'

    date:
        timezone: Europe/Paris

    globals:
        parameters:
            email: '%email%'
            phone: '%phone%'
            postal_address: '%postal_address%'

        social_network:
            facebook: "https://www.facebook.com/ArchersdeCaen"
            instagram: "https://www.instagram.com/archerscaen/"
            youtube: "https://www.youtube.com/channel/UCkbHDxHZnQmr05kvKf5mqkQ"
            tiktok: "https://www.tiktok.com/@archersdecaen2"

        router:
            request_context:
                scheme: '%router.request_context.scheme%'
                host: '%router.request_context.host%'

when@test:
    twig:
        strict_variables: true
