twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'form/ckeditor.html.twig'
        - 'form/gallery.html.twig'
        - 'form/theme.html.twig'

    globals:
        parameters:
            email: '%email%'
            phone: '%phone%'
            postal_address: '%postal_address%'

when@test:
    twig:
        strict_variables: true
