twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'form/ckeditor.html.twig'
        - 'form/gallery.html.twig'
        - 'form/theme.html.twig'

    date:
        timezone: Europe/Paris

    globals:
        environment: '%kernel.environment%'

        parameters:
            email: '%email%'
            phone: '%phone%'
            postal_address: '%postal_address%'

        router:
            request_context:
                scheme: '%router.request_context.scheme%'
                host: '%router.request_context.host%'

when@test:
    twig:
        strict_variables: true
