vich_uploader:
  db_driver: orm

  mappings:
    photo:
      uri_prefix: /images/photo
      upload_destination: '%kernel.project_dir%/public/images/photo'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    document:
      uri_prefix: /document
      upload_destination: '%kernel.project_dir%/public/document'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
