version: "3.4"

services:
  php:
    image: app-php
    restart: unless-stopped
    environment:
      SERVER_NAME: localhost, php:443

      # Run "composer require symfony/mercure-bundle" to install and configure the Mercure integration
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
      MERCURE_PUBLIC_URL: https://${SERVER_NAME:-localhost}/.well-known/mercure
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}

      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      TRUSTED_HOSTS: ^${SERVER_NAME:-example\.com|localhost}|php$$

      DATABASE_URL: mysql://app:!ChangeMe!@database:3306/app?serverVersion=8.1&charset=utf8
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp

  database:
    image: mysql:8.1
    environment:
      MYSQL_DATABASE: app

      MYSQL_PASSWORD: "!ChangeMe!"
      MYSQL_ROOT_PASSWORD: "!ChangeMe!"
      MYSQL_USER: app
    volumes:
      - database_data:/var/lib/mysql

  messenger_consume:
    build:
      context: .
      target: frankenphp_messenger
    image: messenger
    depends_on:
      - php
      - database
    restart: unless-stopped
    volumes:
      - messenger_consume_socket:/var/run/php
      - ./:/app
      - ./tools/frankenphp/certs:/etc/caddy/certs:ro
    environment:
      DATABASE_URL: mysql://app:!ChangeMe!@database:3306/app?serverVersion=8.1&charset=utf8
      TRUSTED_PROXIES: 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      TRUSTED_HOSTS: ^example\.com|localhost|caddy$$

volumes:
  caddy_data:
  caddy_config:
  database_data:
  messenger_consume_socket:
