<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20220906205844 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Première migration';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE archer (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', password VARCHAR(191) DEFAULT NULL, last_login DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, first_name VARCHAR(191) NOT NULL, last_name VARCHAR(191) NOT NULL, email VARCHAR(191) DEFAULT NULL, phone VARCHAR(12) DEFAULT NULL, license_number VARCHAR(7) NOT NULL, gender VARCHAR(191) DEFAULT NULL, category VARCHAR(191) DEFAULT NULL, UNIQUE INDEX UNIQ_38AE8374E7927C74 (email), UNIQUE INDEX UNIQ_38AE8374EC7E7152 (license_number), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE archer_license (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', archer_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', license_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', date_start DATETIME NOT NULL, date_end DATETIME NOT NULL, active TINYINT(1) DEFAULT 0 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_83F9B8147940E3 (archer_id), INDEX IDX_83F9B8460F904B (license_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE badge (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', image_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(191) NOT NULL, code VARCHAR(191) NOT NULL, official TINYINT(1) NOT NULL, type VARCHAR(191) NOT NULL, competition_type VARCHAR(191) DEFAULT NULL, level INT NOT NULL, conditions LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_FEF0481D77153098 (code), UNIQUE INDEX UNIQ_FEF0481D3DA5256D (image_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE competition (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', old_id INT DEFAULT NULL, location VARCHAR(191) NOT NULL, date_start DATE NOT NULL COMMENT \'(DC2Type:date_immutable)\', date_end DATE NOT NULL COMMENT \'(DC2Type:date_immutable)\', type VARCHAR(191) NOT NULL, slug VARCHAR(191) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_B50A2CB1989D9B62 (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE competition_register (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', mandate_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', date_start DATE NOT NULL COMMENT \'(DC2Type:date_immutable)\', date_end DATE NOT NULL COMMENT \'(DC2Type:date_immutable)\', types LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', slug VARCHAR(191) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_6E887B3B989D9B62 (slug), UNIQUE INDEX UNIQ_6E887B3B6C1129CD (mandate_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE competition_register_departure (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', competition_register_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', date DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', max_registration INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_B1C7EA7C61D76400 (competition_register_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE competition_register_departure_target (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', departure_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', type VARCHAR(255) NOT NULL, distance INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_DDB057F07704ED06 (departure_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE competition_register_departure_target_archer (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', target_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', club VARCHAR(191) NOT NULL, wheelchair TINYINT(1) NOT NULL, first_year TINYINT(1) NOT NULL, additional_information LONGTEXT DEFAULT NULL, position VARCHAR(127) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, first_name VARCHAR(191) NOT NULL, last_name VARCHAR(191) NOT NULL, email VARCHAR(191) DEFAULT NULL, phone VARCHAR(12) DEFAULT NULL, license_number VARCHAR(7) NOT NULL, gender VARCHAR(191) DEFAULT NULL, category VARCHAR(191) DEFAULT NULL, INDEX IDX_70910F31158E0B66 (target_id), UNIQUE INDEX unique_archer_by_target (target_id, license_number), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contact_request (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', ip VARCHAR(191) NOT NULL, name VARCHAR(191) NOT NULL, email VARCHAR(191) NOT NULL, content VARCHAR(191) NOT NULL, subject VARCHAR(191) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE data (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', created_by_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', code VARCHAR(191) NOT NULL, description LONGTEXT NOT NULL, content LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', form_type VARCHAR(191) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_ADF3F36377153098 (code), INDEX IDX_ADF3F363B03A8386 (created_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', display_text VARCHAR(191) NOT NULL, document_name VARCHAR(191) NOT NULL, document_size INT NOT NULL, document_mime_type VARCHAR(191) NOT NULL, document_original_name VARCHAR(191) NOT NULL, type VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, token VARCHAR(191) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE gallery (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', main_photo_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', title VARCHAR(191) NOT NULL, slug VARCHAR(191) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_472B783A989D9B62 (slug), UNIQUE INDEX UNIQ_472B783AA7BC5DF9 (main_photo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE license (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', title VARCHAR(191) NOT NULL, price INT NOT NULL, type VARCHAR(191) NOT NULL, description LONGTEXT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE page (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', created_by_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', image_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', title VARCHAR(191) NOT NULL, slug VARCHAR(191) NOT NULL, content LONGTEXT NOT NULL, category VARCHAR(191) NOT NULL, status VARCHAR(191) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_140AB620989D9B62 (slug), INDEX IDX_140AB620B03A8386 (created_by_id), UNIQUE INDEX UNIQ_140AB6203DA5256D (image_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE page_tag (page_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', tag_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', INDEX IDX_CF36BF12C4663E4 (page_id), INDEX IDX_CF36BF12BAD26311 (tag_id), PRIMARY KEY(page_id, tag_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE photo (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', gallery_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', image_name VARCHAR(191) NOT NULL, image_size INT NOT NULL, image_mime_type VARCHAR(191) NOT NULL, image_original_name VARCHAR(191) NOT NULL, image_dimension LONGTEXT NOT NULL COMMENT \'(DC2Type:simple_array)\', created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, token VARCHAR(191) NOT NULL, INDEX IDX_14B784184E7AF8F (gallery_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE result (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', archer_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', score INT NOT NULL, rank INT DEFAULT NULL, category VARCHAR(191) DEFAULT NULL, record TINYINT(1) NOT NULL, weapon VARCHAR(191) NOT NULL, completion_date DATE NOT NULL COMMENT \'(DC2Type:date_immutable)\', created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, type VARCHAR(255) NOT NULL, INDEX IDX_136AC113147940E3 (archer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE result_badge (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', badge_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', INDEX IDX_6F041F91F7A2C2FC (badge_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE result_competition (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', competition_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', INDEX IDX_A39EB8FE7B39D312 (competition_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE result_team (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', competition_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', duels LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', final_rankings LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', INDEX IDX_54DBBD517B39D312 (competition_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE result_team_archer (result_team_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', archer_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', INDEX IDX_582150E24B555A4A (result_team_id), INDEX IDX_582150E2147940E3 (archer_id), PRIMARY KEY(result_team_id, archer_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tag (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(191) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE archer_license ADD CONSTRAINT FK_83F9B8147940E3 FOREIGN KEY (archer_id) REFERENCES archer (id)');
        $this->addSql('ALTER TABLE archer_license ADD CONSTRAINT FK_83F9B8460F904B FOREIGN KEY (license_id) REFERENCES license (id)');
        $this->addSql('ALTER TABLE badge ADD CONSTRAINT FK_FEF0481D3DA5256D FOREIGN KEY (image_id) REFERENCES photo (id)');
        $this->addSql('ALTER TABLE competition_register ADD CONSTRAINT FK_6E887B3B6C1129CD FOREIGN KEY (mandate_id) REFERENCES document (id)');
        $this->addSql('ALTER TABLE competition_register_departure ADD CONSTRAINT FK_B1C7EA7C61D76400 FOREIGN KEY (competition_register_id) REFERENCES competition_register (id)');
        $this->addSql('ALTER TABLE competition_register_departure_target ADD CONSTRAINT FK_DDB057F07704ED06 FOREIGN KEY (departure_id) REFERENCES competition_register_departure (id)');
        $this->addSql('ALTER TABLE competition_register_departure_target_archer ADD CONSTRAINT FK_70910F31158E0B66 FOREIGN KEY (target_id) REFERENCES competition_register_departure_target (id)');
        $this->addSql('ALTER TABLE data ADD CONSTRAINT FK_ADF3F363B03A8386 FOREIGN KEY (created_by_id) REFERENCES archer (id)');
        $this->addSql('ALTER TABLE gallery ADD CONSTRAINT FK_472B783AA7BC5DF9 FOREIGN KEY (main_photo_id) REFERENCES photo (id)');
        $this->addSql('ALTER TABLE page ADD CONSTRAINT FK_140AB620B03A8386 FOREIGN KEY (created_by_id) REFERENCES archer (id)');
        $this->addSql('ALTER TABLE page ADD CONSTRAINT FK_140AB6203DA5256D FOREIGN KEY (image_id) REFERENCES photo (id)');
        $this->addSql('ALTER TABLE page_tag ADD CONSTRAINT FK_CF36BF12C4663E4 FOREIGN KEY (page_id) REFERENCES page (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE page_tag ADD CONSTRAINT FK_CF36BF12BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE photo ADD CONSTRAINT FK_14B784184E7AF8F FOREIGN KEY (gallery_id) REFERENCES gallery (id)');
        $this->addSql('ALTER TABLE result ADD CONSTRAINT FK_136AC113147940E3 FOREIGN KEY (archer_id) REFERENCES archer (id)');
        $this->addSql('ALTER TABLE result_badge ADD CONSTRAINT FK_6F041F91F7A2C2FC FOREIGN KEY (badge_id) REFERENCES badge (id)');
        $this->addSql('ALTER TABLE result_badge ADD CONSTRAINT FK_6F041F91BF396750 FOREIGN KEY (id) REFERENCES result (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE result_competition ADD CONSTRAINT FK_A39EB8FE7B39D312 FOREIGN KEY (competition_id) REFERENCES competition (id)');
        $this->addSql('ALTER TABLE result_competition ADD CONSTRAINT FK_A39EB8FEBF396750 FOREIGN KEY (id) REFERENCES result (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE result_team ADD CONSTRAINT FK_54DBBD517B39D312 FOREIGN KEY (competition_id) REFERENCES competition (id)');
        $this->addSql('ALTER TABLE result_team ADD CONSTRAINT FK_54DBBD51BF396750 FOREIGN KEY (id) REFERENCES result (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE result_team_archer ADD CONSTRAINT FK_582150E24B555A4A FOREIGN KEY (result_team_id) REFERENCES result_team (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE result_team_archer ADD CONSTRAINT FK_582150E2147940E3 FOREIGN KEY (archer_id) REFERENCES archer (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->throwIrreversibleMigrationException();
    }
}
