version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass ${YOUR_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis-net
    sysctls:
      - net.core.somaxconn=511
    ulimits:
      memlock:
        soft: -1
        hard: -1
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  redis-net:
    driver: bridge

volumes:
    redis-data:
        driver: local
