controllers_landing:
    resource: ../src/Http/Landing/Controller
    type: attribute
    prefix: '/'

controllers_app:
    resource: ../src/Http/App/Controller
    type: attribute
    prefix: '/app'

controllers_admin:
    resource: ../src/Http/Admin/Controller
    type: attribute
    prefix: '/admin'

controllers_api:
    resource: ../src/Http/Api/Controller
    type: attribute
    prefix: '/api'

controllers_webhook:
    resource: ../src/Http/Webhook/Controller
    type: attribute
    prefix: '/webhook'

kernel:
    resource: ../src/Kernel.php
    type: attribute
