name: Mise en production

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on production
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://deploy.archers-caen.fr'
          method: 'POST'
          customHeaders: '{"Authorization": "${{ secrets.DEPLOY_PASSWORD }}"}'
