name: Symfony Tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: "Décompression des dépendances"
        uses: montudor/action-zip@v1
        with:
          args: unzip -qq build.zip

      - name: Phpstan
        run: vendor/bin/phpstan analyse -c tools/phpstan/phpstan.neon

  rector:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: "Décompression des dépendances"
        uses: montudor/action-zip@v1
        with:
          args: unzip -qq build.zip

      - name: Rector
        run: |
          RESULT=$(vendor/bin/rector process src --dry-run)

          if [[ $RESULT != *"[OK] Rector is done!"* ]]; then
            echo "Rector found some issues"
            echo "$RESULT"
            exit 1
          fi

