name: Symfony Tests

on:
  push:
    branches: [ "master", "develop", "production" ]
  pull_request:
    branches: [ "master", "develop", "production" ]

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/_build.yml

  tests:
    needs:
      - build
    uses: ./.github/workflows/_phpunit.yml

  lint:
    needs:
      - build
    uses: ./.github/workflows/_lint.yml
